# DB 연결
DATABASE_URL = "postgresql+psycopg://riskuser:riskpass@127.0.0.1:5432/riskdb"

# Gemini API
GEMINI_API_KEY = "AIzaSyD16dEsjlVFLjscp55XNg72Rh84z143w54"
GEMINI_MODEL   = "gemini-2.5-flash"   # 또는 "gemini-2.5-pro"